name: Remove needinfo label

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove needinfo label
        uses: octokit/request-action@v2.x
        continue-on-error: true
        with:
          route: DELETE /repos/:repository/issues/:issue/labels/:label
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          label: needinfo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
